### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by luckylucy1233** [vue-bulma/nprogress#1]
```
Module not found: Error: Can't resolve 'vue-nprogress/src/NprogressContainer'
```

不知道什么情况。

**Comment by fundon** [comment]
@luckylucy1233 你是自己开发的，还是在用 `vue-admin` ？ `vue-admin`@`next` 分支用了 `webpack v2 beta` 很多问题，周末会集中精力处理编译的问题，如果解决不了，就会回退到 `webpack v1`。

**Comment by fundon** [comment]
请参考 [vue-admin](https://github.com/fundon/vue-admin) 的配置

**Comment by eeve** [comment]
@luckylucy1233 
```js
{
        test: /\.vue$/,
        use: 'vue-loader'
        // exclude: /node_modules/
},
```
