### ISSUE TITLE
Set parent does not work!

### ISSUE THREAD

**Issue by paraself** [vue-bulma/nprogress#11]
```javascript
this.$nprogress.configure({parent: 'div.mu-calendar-container'})
```
In some of my vue methods, I tried to set the parent container, but it does not work nor give any error info.
Is there anything that I missed?
Thanks

**Comment by ewfian** [comment]
you can do it like this：
```
new Vue({
  el: '#app',
  nprogress,
  template: '<App/>',
  components: {
    App
  },
  mounted() {
    this.$nextTick(() => {
      this.$nprogress.configure({
        parent: '#nprogress-container'
      })
    });
  }
})
```

**Comment by paraself** [comment]
Thanks, I found that it was a bug of mine. 
```'div.mu-calendar-container'``` is not present when I tried to set the parent. It'll be very helpful If more informative bug information could be provided. ;D
