### ISSUE TITLE
axios may not be defined as Vue.axios (e.g. when using with Laravel)

### ISSUE THREAD

**Issue by willbrowningme** [vue-bulma/nprogress#13]
For anyone using nprogress with Laravel + Vue you may have run into the same issue I did where axios is defined by Laravel as window.axios.

This means that in vue-nprogress/dist/vue-nprogress.js 

```
if (applyOnHttp) {
     var http = Vue.http;
     var axios = Vue.axios;
....
```
var axios is undefined. To solve this you can simply copy vue-nprogress/dist/vue-nprogress.js to the laravel resources/js folder or wherever you choose, change it to below and then import this in app.js instead of importing it from node-modules. 
```
if (applyOnHttp) {
     var http = Vue.http;
     var axios = window.axios;
....
```
This got it working perfectly for me.

**Comment by zanematthew** [comment]
Hi, @nitradesign 

Thanks for posting. I came across your issue when I noticed a discrepancy between the loading of ajax content and the progress, did a quick search in the repo and say your solution.

However I went with a "best practices" approach, using `axios.interceptors`, more below.

This is discussed here; #9, and here on the Axios repo; https://github.com/mzabriskie/axios#interceptors


```
// Disable the default http, and router option.
Vue.use(NProgress, {
    http: false,
    router: false
});
```

```
const app = new Vue({
  nprogress,
  created: function () {
    axios.interceptors.request.use(function (config) {
        nprogress.start();
        return config;
    }, function (error) {
        return Promise.reject(error);
    });
    axios.interceptors.response.use(function (response) {
        nprogress.done();
        return response;
    }, function (error) {
        return Promise.reject(error);
    });
  }
}).$mount('#app');
```
