### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by icangku** [vue-bulma/nprogress#18]
app.js
`import NProgress from 'vue-nprogress'`
`Vue.use(NProgress)`
`const nprogress = new NProgress({ parent: '.nprogress-container' })`
`const app = new Vue({
    el: '#app',
    components: { App, nprogress},
    router,
});`

App.vue
`<nprogress-container></nprogress-container>`
`import NprogressContainer from 'vue-nprogress/src/NprogressContainer'`
`export default {
    name : 'app',
    components : {
        NprogressContainer
    },`

**Comment by akadlec** [comment]
```
const app = new Vue({
el: '#app',
router,
nprogress,
components: { App }
});
```

**Comment by bbugh** [comment]
Just use NProgress package manually. There's absolutely no reason to install this package. 

In `router.js`:

```javascript
import NProgress from 'nprogress'
router.beforeEach((to, from, next) => {
  NProgress.start()
  next()
})
router.afterEach(() => {
  NProgress.done(true)
})
```

In `main.js`:

`import 'nprogress/nprogress.css'`

And you're done.

**Comment by NicksonYap** [comment]
@bbugh that worked :)

**Comment by lloydjatkinson** [comment]
`There's absolutely no reason to install this package.`

Oh, so Vue Router is the only reason you'd ever use NProgress with Vue? Got it.

**Comment by bbugh** [comment]
@lloydjatkinson No need to be so rude. The purpose of plugin packages is to make them easier to use with Vue, but `NProgress` is already very easy to use. The package is currently also broken, which makes it not work at all. If you have a use case that this package benefits from, then by all means install it, but I expect most people who are using it aren't going to need it.

**Comment by lloydjatkinson** [comment]
I think stating "There's absolutely no reason to install this package." about someones work is pretty rude, and far ruder than my response to your comment.

**Comment by icangku** [comment]
`  mounted(){
    this.$parent.$parent.$refs.topProgress.start()
  }
this.$parent.$parent.$parent.$refs.topProgress.done()
`
